// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function SendMessageInput(arg1) {
  return window['go']['main']['App']['SendMessageInput'](arg1);
}
