// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';

export function CreateSession():Promise<terminal.TerminalSession>;

export function SendMessageInput(arg1:string):Promise<terminal.TerminalSession>;
